name: SonarQube
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Compilar, testar e analisar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clones rasos devem ser desativados para melhor análise

      - name: Tornar o gradlew executável
        run: chmod +x ./gradlew

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache de pacotes do SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache de pacotes do Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Compilar projeto
        run: ./gradlew build --info

      - name: Rodar testes e gerar cobertura
        run: ./gradlew test jacocoTestReport

      - name: Analisar com SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info

      - name: Publicar relatórios de qualidade
        uses: actions/upload-artifact@v3
        with:
          name: relatorios-qualidade
          path: |
            build/reports/tests/test
            build/reports/jacoco
            build/reports/sonar
